events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile    on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

        # 静态资源（HTML 页面等，直接由 nginx 提供服务）
        location /static/ {
            alias /usr/share/nginx/static/;
            charset utf-8;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;

            # 让其他文件在浏览器中直接显示，而非触发下载
            default_type text/plain;
        }
    }
}
